name: uber_black_app
description: App para simular fluxo Uber Black
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.3.0
  url_launcher: ^6.1.7

flutter:
  uses-material-design: true
